# Generated by Django 5.0.4 on 2024-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("NationalITy", models.CharField(max_length=50)),
                ("PlaceofBirth", models.CharField(max_length=50)),
                ("StageID", models.CharField(max_length=20)),
                ("GradeID", models.CharField(max_length=4)),
                ("SectionID", models.CharField(max_length=1)),
                ("Topic", models.CharField(max_length=50)),
                (
                    "Semester",
                    models.CharField(
                        choices=[("F", "First"), ("S", "Second")], max_length=1
                    ),
                ),
                (
                    "Relation",
                    models.CharField(
                        choices=[("Father", "Father"), ("Mum", "Mum")], max_length=6
                    ),
                ),
                ("raisedhands", models.IntegerField()),
                ("VisITedResources", models.IntegerField()),
                ("AnnouncementsView", models.IntegerField()),
                ("Discussion", models.IntegerField()),
                ("ParentAnsweringSurvey", models.CharField(max_length=3)),
                ("ParentschoolSatisfaction", models.CharField(max_length=4)),
                (
                    "StudentAbsenceDays",
                    models.CharField(
                        choices=[("Under-7", "Under 7"), ("Above-7", "Above 7")],
                        max_length=7,
                    ),
                ),
            ],
        ),
    ]
