# Generated by Django 5.0.4 on 2024-04-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("frontend_ml", "0002_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=10)),
                ("nationality", models.CharField(max_length=50)),
                ("place_of_birth", models.CharField(max_length=50)),
                ("stage_id", models.CharField(max_length=50)),
                ("grade_id", models.CharField(max_length=50)),
                ("section_id", models.CharField(max_length=10)),
                ("topic", models.CharField(max_length=50)),
                ("semester", models.CharField(max_length=10)),
                ("relation", models.CharField(max_length=50)),
                ("raised_hands", models.IntegerField()),
                ("visited_resources", models.IntegerField()),
                ("announcements_view", models.IntegerField()),
                ("discussion", models.IntegerField()),
                ("parent_answering_survey", models.CharField(max_length=10)),
                ("parent_school_satisfaction", models.CharField(max_length=50)),
                ("student_absence_days", models.CharField(max_length=50)),
                ("class_label", models.CharField(max_length=10)),
            ],
        ),
    ]
