# Generated by Django 5.0.4 on 2024-04-26 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend_ml", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
