# Generated by Django 5.0.4 on 2024-04-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("frontend_ml", "0004_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=1)),
                ("NationalITy", models.CharField(max_length=50)),
                ("PlaceofBirth", models.CharField(max_length=50)),
                ("StageID", models.CharField(max_length=50)),
                ("GradeID", models.CharField(max_length=10)),
                ("SectionID", models.CharField(max_length=10)),
                ("Topic", models.CharField(max_length=50)),
                ("Semester", models.CharField(max_length=1)),
                ("Relation", models.CharField(max_length=50)),
                ("raisedhands", models.IntegerField()),
                ("VisITedResources", models.IntegerField()),
                ("AnnouncementsView", models.IntegerField()),
                ("Discussion", models.IntegerField()),
                ("ParentAnsweringSurvey", models.CharField(max_length=3)),
                ("ParentschoolSatisfaction", models.CharField(max_length=4)),
                ("StudentAbsenceDays", models.CharField(max_length=10)),
                ("Class", models.CharField(max_length=1)),
            ],
        ),
    ]
